# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ThreeD_viewer.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1920, 1125)
        font = QtGui.QFont()
        font.setUnderline(False)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(1920, 1080))
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        font.setUnderline(False)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtWidgets.QSplitter(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.frame = QtWidgets.QFrame(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.frame.setFont(font)
        self.frame.setAutoFillBackground(True)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayoutWidget = QtWidgets.QWidget(self.frame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 90, 345, 151))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton2.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.pushButton2.setFont(font)
        self.pushButton2.setObjectName("pushButton2")
        self.gridLayout_2.addWidget(self.pushButton2, 1, 2, 1, 1)
        self.toolButton1 = QtWidgets.QToolButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton1.sizePolicy().hasHeightForWidth())
        self.toolButton1.setSizePolicy(sizePolicy)
        self.toolButton1.setMinimumSize(QtCore.QSize(20, 20))
        self.toolButton1.setBaseSize(QtCore.QSize(50, 50))
        self.toolButton1.setObjectName("toolButton1")
        self.gridLayout_2.addWidget(self.toolButton1, 0, 1, 1, 1, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.BtnClear = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.BtnClear.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.BtnClear.setFont(font)
        self.BtnClear.setObjectName("BtnClear")
        self.gridLayout_2.addWidget(self.BtnClear, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.toolButton2 = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.toolButton2.setObjectName("toolButton2")
        self.gridLayout_2.addWidget(self.toolButton2, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 2, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(0, 0, 291, 91))
        self.label_6.setStyleSheet("color:rgb(170, 170, 0)")
        self.label_6.setTextFormat(QtCore.Qt.AutoText)
        self.label_6.setScaledContents(False)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setGeometry(QtCore.QRect(0, 70, 291, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setGeometry(QtCore.QRect(0, 390, 371, 231))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalSlider_2 = QtWidgets.QSlider(self.groupBox)
        self.verticalSlider_2.setEnabled(False)
        self.verticalSlider_2.setGeometry(QtCore.QRect(30, 70, 21, 151))
        self.verticalSlider_2.setMaximum(100)
        self.verticalSlider_2.setProperty("value", 100)
        self.verticalSlider_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_2.setObjectName("verticalSlider_2")
        self.verticalSlider = QtWidgets.QSlider(self.groupBox)
        self.verticalSlider.setEnabled(False)
        self.verticalSlider.setGeometry(QtCore.QRect(80, 70, 21, 151))
        self.verticalSlider.setMaximum(100)
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName("verticalSlider")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(10, 40, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(60, 40, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.resetCam = QtWidgets.QPushButton(self.groupBox)
        self.resetCam.setEnabled(False)
        self.resetCam.setGeometry(QtCore.QRect(150, 60, 75, 23))
        self.resetCam.setObjectName("resetCam")
        self.topView = QtWidgets.QPushButton(self.groupBox)
        self.topView.setEnabled(False)
        self.topView.setGeometry(QtCore.QRect(150, 100, 75, 23))
        self.topView.setObjectName("topView")
        self.leftView = QtWidgets.QPushButton(self.groupBox)
        self.leftView.setEnabled(False)
        self.leftView.setGeometry(QtCore.QRect(110, 130, 75, 23))
        self.leftView.setObjectName("leftView")
        self.rightView = QtWidgets.QPushButton(self.groupBox)
        self.rightView.setEnabled(False)
        self.rightView.setGeometry(QtCore.QRect(190, 130, 75, 23))
        self.rightView.setObjectName("rightView")
        self.thetaX = QtWidgets.QTextEdit(self.groupBox)
        self.thetaX.setGeometry(QtCore.QRect(280, 60, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(6)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.thetaX.setFont(font)
        self.thetaX.setObjectName("thetaX")
        self.thetaY = QtWidgets.QTextEdit(self.groupBox)
        self.thetaY.setGeometry(QtCore.QRect(280, 100, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(6)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.thetaY.setFont(font)
        self.thetaY.setObjectName("thetaY")
        self.thetaZ = QtWidgets.QTextEdit(self.groupBox)
        self.thetaZ.setGeometry(QtCore.QRect(280, 140, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(6)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.thetaZ.setFont(font)
        self.thetaZ.setObjectName("thetaZ")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(290, 45, 61, 16))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(290, 85, 61, 16))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(290, 120, 61, 21))
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.applyTransform = QtWidgets.QPushButton(self.groupBox)
        self.applyTransform.setEnabled(False)
        self.applyTransform.setGeometry(QtCore.QRect(280, 170, 81, 23))
        self.applyTransform.setObjectName("applyTransform")
        self.isPerspective = QtWidgets.QCheckBox(self.groupBox)
        self.isPerspective.setGeometry(QtCore.QRect(120, 200, 111, 16))
        self.isPerspective.setObjectName("isPerspective")
        self.pointPicker = QtWidgets.QCheckBox(self.groupBox)
        self.pointPicker.setGeometry(QtCore.QRect(260, 200, 101, 16))
        self.pointPicker.setAcceptDrops(True)
        self.pointPicker.setObjectName("pointPicker")
        self.progressBar = QtWidgets.QProgressBar(self.frame)
        self.progressBar.setGeometry(QtCore.QRect(-3, 630, 381, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 239, 371, 141))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.detailView = QtWidgets.QTextEdit(self.groupBox_2)
        self.detailView.setGeometry(QtCore.QRect(3, 30, 361, 101))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.detailView.sizePolicy().hasHeightForWidth())
        self.detailView.setSizePolicy(sizePolicy)
        self.detailView.setTabletTracking(True)
        self.detailView.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.detailView.setAcceptDrops(False)
        self.detailView.setAutoFillBackground(True)
        self.detailView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.detailView.setAutoFormatting(QtWidgets.QTextEdit.AutoAll)
        self.detailView.setTabChangesFocus(True)
        self.detailView.setReadOnly(True)
        self.detailView.setObjectName("detailView")
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.vtk_panel = QtWidgets.QFrame(self.splitter)
        self.vtk_panel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.vtk_panel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.vtk_panel.setObjectName("vtk_panel")
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab2.sizePolicy().hasHeightForWidth())
        self.tab2.setSizePolicy(sizePolicy)
        self.tab2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tab2.setObjectName("tab2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_4 = QtWidgets.QLabel(self.tab2)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(14)
        font.setUnderline(False)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem2, 0, 3, 1, 1)
        self.PlytoMesh = QtWidgets.QPushButton(self.tab2)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(14)
        font.setUnderline(False)
        self.PlytoMesh.setFont(font)
        self.PlytoMesh.setObjectName("PlytoMesh")
        self.gridLayout_5.addWidget(self.PlytoMesh, 1, 0, 1, 1)
        self.toolButton1_2 = QtWidgets.QToolButton(self.tab2)
        self.toolButton1_2.setObjectName("toolButton1_2")
        self.gridLayout_5.addWidget(self.toolButton1_2, 0, 1, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.tab2)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(14)
        font.setUnderline(False)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_5.addWidget(self.checkBox, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_5)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_5 = QtWidgets.QLabel(self.tab2)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(14)
        font.setUnderline(False)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 0, 4, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.tab2)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(14)
        font.setUnderline(False)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_4.addWidget(self.pushButton, 1, 0, 1, 1)
        self.toolButton1_3 = QtWidgets.QToolButton(self.tab2)
        self.toolButton1_3.setObjectName("toolButton1_3")
        self.gridLayout_4.addWidget(self.toolButton1_3, 0, 1, 1, 1)
        self.SaveMeshTo = QtWidgets.QPushButton(self.tab2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SaveMeshTo.sizePolicy().hasHeightForWidth())
        self.SaveMeshTo.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(14)
        font.setUnderline(False)
        self.SaveMeshTo.setFont(font)
        self.SaveMeshTo.setObjectName("SaveMeshTo")
        self.gridLayout_4.addWidget(self.SaveMeshTo, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_4)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.tab2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3.addWidget(self.frame_3, 1, 1, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.tab2)
        self.frame_2.setEnabled(True)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3.addWidget(self.frame_2, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab2, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "3D viewer (Beta)"))
        self.pushButton2.setText(_translate("MainWindow", "Output"))
        self.toolButton1.setText(_translate("MainWindow", "..."))
        self.BtnClear.setText(_translate("MainWindow", "Clear XYZ"))
        self.label.setText(_translate("MainWindow", "Add Raw"))
        self.toolButton2.setText(_translate("MainWindow", "..."))
        self.label_3.setText(_translate("MainWindow", "Add XYZ"))
        self.label_6.setText(_translate("MainWindow", "Benano"))
        self.groupBox.setTitle(_translate("MainWindow", "Controller"))
        self.label_7.setText(_translate("MainWindow", "Max"))
        self.label_8.setText(_translate("MainWindow", "Min"))
        self.resetCam.setText(_translate("MainWindow", "Y Up"))
        self.topView.setText(_translate("MainWindow", "Z Up"))
        self.leftView.setText(_translate("MainWindow", "-"))
        self.rightView.setText(_translate("MainWindow", "+"))
        self.thetaX.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Courier New\'; font-size:6pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>"))
        self.thetaY.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Courier New\'; font-size:6pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>"))
        self.thetaZ.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Courier New\'; font-size:6pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "θx"))
        self.label_10.setText(_translate("MainWindow", "θy"))
        self.label_11.setText(_translate("MainWindow", "θz"))
        self.applyTransform.setText(_translate("MainWindow", "Apply"))
        self.isPerspective.setText(_translate("MainWindow", "Parellel View"))
        self.pointPicker.setText(_translate("MainWindow", "Pick Points"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Detail"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Basic"))
        self.label_4.setText(_translate("MainWindow", "Add Pointcloud"))
        self.PlytoMesh.setText(_translate("MainWindow", "PLY to Mesh"))
        self.toolButton1_2.setText(_translate("MainWindow", "..."))
        self.checkBox.setText(_translate("MainWindow", "Sync Views"))
        self.label_5.setText(_translate("MainWindow", "Add Mesh(*.ply)"))
        self.pushButton.setText(_translate("MainWindow", "Smooth Test"))
        self.toolButton1_3.setText(_translate("MainWindow", "..."))
        self.SaveMeshTo.setText(_translate("MainWindow", "Save Mesh To"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("MainWindow", "Points and Mesh"))
